steps:
  - name: node:18
    entrypoint: npm
    args: ["ci"]

  - name: node:18
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
      - "NEXT_TELEMETRY_DISABLED=1"
      - 'FIREBASE_CONFIG={"projectId":"$PROJECT_ID","databaseURL":"$_DATABASE_URL"}'

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BUILD_ID=$BUILD_ID",
        "--network",
        "cloudbuild",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/run/nextjs-on-gcp",
        ".",
      ]

  - name: "us-central1-docker.pkg.dev/$PROJECT_ID/run/firebase"
    entrypoint: "bash"
    args: ["./scripts/firebase-deploy.sh"]
    env:
      - "PROJECT_ID=$PROJECT_ID"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/run/nextjs-on-gcp"

options:
  dynamicSubstitutions: true

substitutions:
  _DATABASE_URL: "https://${PROJECT_ID}-default-rtdb.firebaseio.com"
