steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target",
        "runner",
        '--build-arg="BUILD_ID=$BUILD_ID"',
        '--build-arg="GCS_BUCKET_NAME=$_GCS_BUCKET_NAME"',
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/run/nextjs-on-gcp",
        ".",
      ]
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--target", "export", "-o", "/workspace/.next", "."]
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/gcloud-slim"
    args:
      [
        "storage",
        "cp",
        "--recursive",
        "/workspace/.next",
        "gs://$PROJECT_ID/app/$BUILD_ID",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/run/nextjs-on-gcp"

substitutions:
  _GCS_BUCKET_NAME: "$PROJECT_ID"
